# @format

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.yarnpkg.com'

      - name: install
        run: yarn install

      - name: install
        run: cd tsExample && yarn install

      - name: test
        run: yarn testTS
